server:
  port: 8081

spring:
    application.name: cunsumer-demo
    profiles.active: dev
    dubbo:
        application.name: cunsumer-demo
        registry.address: zookeeper://127.0.0.1:2181
        protocol:
            name: dubbo
            port: 20880
        scan: service
logging:
  path: logs
  level:
    com.leadingsoft.demo: DEBUG
    org.springframework: WARN
